name: 'MkDocs S3 Pages Publisher'
description: 'Publish your MkDocs pages to a SimpleStorageServer(S3) bucket'
author: 'Thorsten Schifferdecker, ts@systs.org'
branding:
  icon: 'book'
  color: 'blue'
runs:
  using: "composite"
  steps:
    - name: Setup mkdocs
      run: pip install --no-cache-dir -r "${{ github.action_path }}/requirements.txt"
      shell: bash
    - name: Build mkdocs pages and publish to S3 bucket
      run: ${{ github.action_path }}/action.sh
      shell: bash